-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 21:01:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`clientes` (
  `id_Clientes` INT NOT NULL,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_Clientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`empleados` (
  `id_empleados` INT NOT NULL,
  `nombreCompleto` VARCHAR(60) NULL DEFAULT NULL,
  `nombreUsuario` VARCHAR(60) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `rol` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_Actualizacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`proveedores` (
  `id_proveedores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `ciudad` VARCHAR(60) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`compras` (
  `id_Compras` INT NOT NULL AUTO_INCREMENT,
  `proveedorID_FK` INT NULL DEFAULT NULL,
  `empleadoId_FK` INT NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `fecha_compra` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_Compras`),
  INDEX `compras_idx` (`empleadoId_FK` ASC) VISIBLE,
  INDEX `proveedorID_FK_idx` (`proveedorID_FK` ASC) VISIBLE,
  CONSTRAINT `compras`
    FOREIGN KEY (`empleadoId_FK`)
    REFERENCES `farmacia`.`empleados` (`id_empleados`),
  CONSTRAINT `proveedorID_FK`
    FOREIGN KEY (`proveedorID_FK`)
    REFERENCES `farmacia`.`proveedores` (`id_proveedores`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `categoria_FK` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_productos`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `category_id_idx` (`categoria_FK` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`categoria_FK`)
    REFERENCES `farmacia`.`categorias` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`detalles_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`detalles_compra` (
  `idDetalles_compra` INT NOT NULL AUTO_INCREMENT,
  `precio_compra` DOUBLE NULL DEFAULT NULL,
  `cantidad_compra` INT NULL DEFAULT NULL,
  `total_compra` DOUBLE NULL DEFAULT NULL,
  `compraID_FK` INT NULL DEFAULT NULL,
  `productoID_FK` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalles_compra`),
  INDEX `compraID_FK_idx` (`compraID_FK` ASC) VISIBLE,
  INDEX `productoID_FK_idx` (`productoID_FK` ASC) VISIBLE,
  CONSTRAINT `compraID_FK`
    FOREIGN KEY (`compraID_FK`)
    REFERENCES `farmacia`.`compras` (`id_Compras`),
  CONSTRAINT `productoID_FK`
    FOREIGN KEY (`productoID_FK`)
    REFERENCES `farmacia`.`productos` (`id_productos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`ventas` (
  `id_ventas` INT NOT NULL,
  `Fecha_venta` DATETIME NULL DEFAULT NULL,
  `total_venta` DOUBLE NULL DEFAULT NULL,
  `clientesID_Fk` INT NULL DEFAULT NULL,
  `empleadoId_FK` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `clientesID_Fk_idx` (`clientesID_Fk` ASC) VISIBLE,
  INDEX `empleadoId_FK_idx` (`empleadoId_FK` ASC) VISIBLE,
  CONSTRAINT `clientesID_Fk`
    FOREIGN KEY (`clientesID_Fk`)
    REFERENCES `farmacia`.`clientes` (`id_Clientes`),
  CONSTRAINT `empleadoId_FK`
    FOREIGN KEY (`empleadoId_FK`)
    REFERENCES `farmacia`.`empleados` (`id_empleados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia`.`detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`detalles_venta` (
  `idDetalles_venta` INT NOT NULL,
  `Cantidad_venta` INT NULL DEFAULT NULL,
  `precio_venta` DOUBLE NULL DEFAULT NULL,
  `subTotal_venta` DOUBLE NULL DEFAULT NULL,
  `productosID_FK` INT NULL DEFAULT NULL,
  `ventasID_Fk` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalles_venta`),
  INDEX `productoID_FK_idx` (`productosID_FK` ASC) VISIBLE,
  INDEX `ventasID_Fk_idx` (`ventasID_Fk` ASC) VISIBLE,
  CONSTRAINT `productosID_FK`
    FOREIGN KEY (`productosID_FK`)
    REFERENCES `farmacia`.`productos` (`id_productos`),
  CONSTRAINT `ventasID_Fk`
    FOREIGN KEY (`ventasID_Fk`)
    REFERENCES `farmacia`.`ventas` (`id_ventas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
